


export const ProductData = [{
    "productID": 1,
    "productTitle": "Ultra Mobile Pro",
    "description": "A powerful smartphone with a sleek design and top-notch performance.",
    "rating": 5,
    "price": 899,
    "seller": "TechWorld",
    "totalSales": 1200,
    "quantityInStock": 450,
    "keyword": "mobile",

},
{
    "productID": 2,
    "productTitle": "Speedy Mobile X",
    "description": "Experience lightning-fast speed with this advanced mobile phone.",
    "rating": 4,
    "price": 749,
    "seller": "GizmoHub",
    "totalSales": 980,
    "quantityInStock": 320,
    "keyword": "mobile",

},
{
    "productID": 3,
    "productTitle": "NextGen Mobile",
    "description": "A mobile device that brings the future to your fingertips.",
    "rating": 5,
    "price": 999,
    "seller": "FutureGadgets",
    "totalSales": 1550,
    "quantityInStock": 230,
    "keyword": "mobile",

},
{
    "productID": 4,
    "productTitle": "Compact Mobile Z",
    "description": "Compact and powerful, perfect for those on the go.",
    "rating": 4,
    "price": 629,
    "seller": "TechWorld",
    "totalSales": 890,
    "quantityInStock": 210,
    "keyword": "mobile",

},
{
    "productID": 5,
    "productTitle": "Mobile XL Max",
    "description": "Extra-large display for an immersive mobile experience.",
    "rating": 3,
    "price": 799,
    "seller": "GadgetPlus",
    "totalSales": 670,
    "quantityInStock": 530,
    "keyword": "mobile",

},
{
    "productID": 6,
    "productTitle": "Pro Mobile Edge",
    "description": "Cutting-edge technology in a sleek mobile device.",
    "rating": 5,
    "price": 879,
    "seller": "TechWorld",
    "totalSales": 1020,
    "quantityInStock": 400,
    "keyword": "mobile",

},
{
    "productID": 7,
    "productTitle": "Essential Mobile 5G",
    "description": "Affordable 5G mobile for everyday use.",
    "rating": 4,
    "price": 599,
    "seller": "GizmoHub",
    "totalSales": 780,
    "quantityInStock": 310,
    "keyword": "mobile",

},
{
    "productID": 8,
    "productTitle": "Mobile Infinity",
    "description": "Endless possibilities with this high-performance mobile.",
    "rating": 5,
    "price": 950,
    "seller": "FutureGadgets",
    "totalSales": 1110,
    "quantityInStock": 290,
    "keyword": "mobile",

},
{
    "productID": 9,
    "productTitle": "Mobile Lite",
    "description": "Lightweight and easy to use mobile device.",
    "rating": 4,
    "price": 499,
    "seller": "GadgetPlus",
    "totalSales": 920,
    "quantityInStock": 460,
    "keyword": "mobile",

},
{
    "productID": 10,
    "productTitle": "Mobile Prime",
    "description": "The prime choice for mobile enthusiasts.",
    "rating": 5,
    "price": 899,
    "seller": "TechWorld",
    "totalSales": 1000,
    "quantityInStock": 370,
    "keyword": "mobile",

},
{
    "productID": 11,
    "productTitle": "Laptop Pro X",
    "description": "High-performance laptop with a sleek design.",
    "rating": 5,
    "price": 999,
    "seller": "TechWorld",
    "totalSales": 850,
    "quantityInStock": 210,
    "keyword": "laptop",

},
{
    "productID": 12,
    "productTitle": "UltraBook Max",
    "description": "Lightweight and powerful laptop for professionals.",
    "rating": 4,
    "price": 899,
    "seller": "GizmoHub",
    "totalSales": 720,
    "quantityInStock": 320,
    "keyword": "laptop",

},
{
    "productID": 13,
    "productTitle": "Gaming Beast",
    "description": "A gaming laptop designed for the ultimate experience.",
    "rating": 5,
    "price": 1299,
    "seller": "FutureGadgets",
    "totalSales": 1150,
    "quantityInStock": 150,
    "keyword": "laptop",

},
{
    "productID": 14,
    "productTitle": "Business Elite",
    "description": "A business-class laptop with top-notch security features.",
    "rating": 4,
    "price": 950,
    "seller": "TechWorld",
    "totalSales": 790,
    "quantityInStock": 280,
    "keyword": "laptop",

},
{
    "productID": 15,
    "productTitle": "Creative Pro",
    "description": "A laptop built for creative professionals.",
    "rating": 5,
    "price": 1100,
    "seller": "GadgetPlus",
    "totalSales": 950,
    "quantityInStock": 220,
    "keyword": "laptop",

},
{
    "productID": 16,
    "productTitle": "Student Laptop",
    "description": "Affordable laptop perfect for students.",
    "rating": 4,
    "price": 750,
    "seller": "TechWorld",
    "totalSales": 680,
    "quantityInStock": 340,
    "keyword": "laptop",

},
{
    "productID": 17,
    "productTitle": "UltraBook Slim",
    "description": "A slim and lightweight laptop for daily use.",
    "rating": 4,
    "price": 850,
    "seller": "GizmoHub",
    "totalSales": 800,
    "quantityInStock": 300,
    "keyword": "laptop",

},
{
    "productID": 18,
    "productTitle": "PowerBook X",
    "description": "A powerful laptop for demanding tasks.",
    "rating": 5,
    "price": 1199,
    "seller": "FutureGadgets",
    "totalSales": 1050,
    "quantityInStock": 190,
    "keyword": "laptop",

},
{
    "productID": 19,
    "productTitle": "Budget Laptop",
    "description": "A budget-friendly laptop with essential features.",
    "rating": 3,
    "price": 600,
    "seller": "GadgetPlus",
    "totalSales": 940,
    "quantityInStock": 410,
    "keyword": "laptop",

},
{
    "productID": 20,
    "productTitle": "Laptop Prime",
    "description": "Top-tier laptop with cutting-edge technology.",
    "rating": 5,
    "price": 1299,
    "seller": "TechWorld",
    "totalSales": 980,
    "quantityInStock": 160,
    "keyword": "laptop",

},
{
    "productID": 21,
    "productTitle": "Wireless Charger",
    "description": "Fast wireless charger for all compatible devices.",
    "rating": 4,
    "price": 150,
    "seller": "GadgetPlus",
    "totalSales": 1200,
    "quantityInStock": 500,
    "keyword": "accessories",

},
{
    "productID": 22,
    "productTitle": "Portable SSD",
    "description": "High-speed portable SSD with 1TB storage.",
    "rating": 5,
    "price": 250,
    "seller": "TechWorld",
    "totalSales": 950,
    "quantityInStock": 400,
    "keyword": "accessories",

},
{
    "productID": 23,
    "productTitle": "Bluetooth Speaker",
    "description": "Compact Bluetooth speaker with superior sound quality.",
    "rating": 4,
    "price": 200,
    "seller": "FutureGadgets",
    "totalSales": 820,
    "quantityInStock": 350,
    "keyword": "accessories",

},
{
    "productID": 24,
    "productTitle": "USB-C Hub",
    "description": "Multi-port USB-C hub for all your connectivity needs.",
    "rating": 4,
    "price": 120,
    "seller": "GizmoHub",
    "totalSales": 980,
    "quantityInStock": 620,
    "keyword": "accessories",

},
{
    "productID": 25,
    "productTitle": "Ergonomic Mouse",
    "description": "Comfortable ergonomic mouse for long hours of use.",
    "rating": 5,
    "price": 170,
    "seller": "GadgetPlus",
    "totalSales": 710,
    "quantityInStock": 420,
    "keyword": "accessories",

},
{
    "productID": 26,
    "productTitle": "Smartphone Stand",
    "description": "Adjustable stand for smartphones and tablets.",
    "rating": 4,
    "price": 100,
    "seller": "TechWorld",
    "totalSales": 670,
    "quantityInStock": 590,
    "keyword": "accessories",

},
{
    "productID": 27,
    "productTitle": "Noise Cancelling Headphones",
    "description": "Premium headphones with active noise cancellation.",
    "rating": 5,
    "price": 300,
    "seller": "FutureGadgets",
    "totalSales": 1100,
    "quantityInStock": 240,
    "keyword": "accessories",

},
{
    "productID": 28,
    "productTitle": "Laptop Sleeve",
    "description": "Protective sleeve for laptops up to 15 inches.",
    "rating": 4,
    "price": 130,
    "seller": "GizmoHub",
    "totalSales": 650,
    "quantityInStock": 470,
    "keyword": "accessories",

},
{
    "productID": 29,
    "productTitle": "Portable Power Bank",
    "description": "High-capacity power bank with fast charging.",
    "rating": 4,
    "price": 200,
    "seller": "GadgetPlus",
    "totalSales": 920,
    "quantityInStock": 530,
    "keyword": "accessories",

},
{
    "productID": 30,
    "productTitle": "Wireless Keyboard",
    "description": "Slim and lightweight wireless keyboard.",
    "rating": 4,
    "price": 180,
    "seller": "TechWorld",
    "totalSales": 880,
    "quantityInStock": 340,
    "keyword": "accessories",

},
{
    "productID": 31,
    "productTitle": "Tablet Pro",
    "description": "A professional-grade tablet for all your needs.",
    "rating": 5,
    "price": 799,
    "seller": "TechWorld",
    "totalSales": 900,
    "quantityInStock": 150,
    "keyword": "tablet",

},
{
    "productID": 32,
    "productTitle": "Mini Tablet X",
    "description": "Compact tablet with powerful performance.",
    "rating": 4,
    "price": 600,
    "seller": "GizmoHub",
    "totalSales": 780,
    "quantityInStock": 280,
    "keyword": "tablet",

},
{
    "productID": 33,
    "productTitle": "Tablet Max",
    "description": "Large display tablet for immersive viewing.",
    "rating": 5,
    "price": 950,
    "seller": "FutureGadgets",
    "totalSales": 1120,
    "quantityInStock": 230,
    "keyword": "tablet",

},
{
    "productID": 34,
    "productTitle": "Tablet Lite",
    "description": "Lightweight and easy to carry tablet.",
    "rating": 4,
    "price": 550,
    "seller": "TechWorld",
    "totalSales": 620,
    "quantityInStock": 370,
    "keyword": "tablet",

},
{
    "productID": 35,
    "productTitle": "Ultra Tablet",
    "description": "High-performance tablet for power users.",
    "rating": 5,
    "price": 1000,
    "seller": "GadgetPlus",
    "totalSales": 980,
    "quantityInStock": 200,
    "keyword": "tablet",

},
{
    "productID": 36,
    "productTitle": "Tablet Pro Lite",
    "description": "Affordable version of the Pro tablet with essential features.",
    "rating": 4,
    "price": 650,
    "seller": "TechWorld",
    "totalSales": 700,
    "quantityInStock": 420,
    "keyword": "tablet",

},
{
    "productID": 37,
    "productTitle": "Gaming Tablet",
    "description": "A tablet designed for mobile gaming enthusiasts.",
    "rating": 5,
    "price": 899,
    "seller": "FutureGadgets",
    "totalSales": 830,
    "quantityInStock": 310,
    "keyword": "tablet",

},
{
    "productID": 38,
    "productTitle": "Tablet Prime",
    "description": "Top-tier tablet with cutting-edge features.",
    "rating": 5,
    "price": 1100,
    "seller": "GizmoHub",
    "totalSales": 670,
    "quantityInStock": 180,
    "keyword": "tablet",

},
{
    "productID": 39,
    "productTitle": "Portable Tablet",
    "description": "A portable tablet with all the essentials.",
    "rating": 4,
    "price": 500,
    "seller": "GadgetPlus",
    "totalSales": 750,
    "quantityInStock": 450,
    "keyword": "tablet",

},
{
    "productID": 40,
    "productTitle": "Tablet Xtreme",
    "description": "High-end tablet for extreme users.",
    "rating": 5,
    "price": 1200,
    "seller": "TechWorld",
    "totalSales": 580,
    "quantityInStock": 170,
    "keyword": "tablet",

},
{
    "productID": 41,
    "productTitle": "Smart Watch X",
    "description": "Advanced smartwatch with fitness tracking features.",
    "rating": 5,
    "price": 450,
    "seller": "GizmoHub",
    "totalSales": 1150,
    "quantityInStock": 370,
    "keyword": "smart watch",

},
{
    "productID": 42,
    "productTitle": "Fitness Watch Pro",
    "description": "A smartwatch designed for fitness enthusiasts.",
    "rating": 4,
    "price": 400,
    "seller": "TechWorld",
    "totalSales": 990,
    "quantityInStock": 250,
    "keyword": "smart watch",

},
{
    "productID": 43,
    "productTitle": "Luxury Smart Watch",
    "description": "A luxurious smartwatch with a premium design.",
    "rating": 5,
    "price": 600,
    "seller": "FutureGadgets",
    "totalSales": 870,
    "quantityInStock": 200,
    "keyword": "smart watch",

},
{
    "productID": 44,
    "productTitle": "Budget Smart Watch",
    "description": "Affordable smartwatch with essential features.",
    "rating": 3,
    "price": 300,
    "seller": "GadgetPlus",
    "totalSales": 1100,
    "quantityInStock": 480,
    "keyword": "smart watch",

},
{
    "productID": 45,
    "productTitle": "Smart Watch Lite",
    "description": "Lightweight smartwatch with a minimalist design.",
    "rating": 4,
    "price": 350,
    "seller": "TechWorld",
    "totalSales": 950,
    "quantityInStock": 310,
    "keyword": "smart watch",

},
{
    "productID": 46,
    "productTitle": "Smart Watch Max",
    "description": "Feature-rich smartwatch with a large display.",
    "rating": 5,
    "price": 550,
    "seller": "GizmoHub",
    "totalSales": 720,
    "quantityInStock": 280,
    "keyword": "smart watch",

},
{
    "productID": 47,
    "productTitle": "Sport Smart Watch",
    "description": "A smartwatch designed for sports enthusiasts.",
    "rating": 4,
    "price": 400,
    "seller": "FutureGadgets",
    "totalSales": 670,
    "quantityInStock": 390,
    "keyword": "smart watch",

},
{
    "productID": 48,
    "productTitle": "Premium Smart Watch",
    "description": "High-end smartwatch with advanced features.",
    "rating": 5,
    "price": 650,
    "seller": "GadgetPlus",
    "totalSales": 1020,
    "quantityInStock": 230,
    "keyword": "smart watch",

},
{
    "productID": 49,
    "productTitle": "Smart Watch Ultra",
    "description": "The ultimate smartwatch with cutting-edge technology.",
    "rating": 5,
    "price": 700,
    "seller": "TechWorld",
    "totalSales": 820,
    "quantityInStock": 210,
    "keyword": "smart watch",

},
{
    "productID": 50,
    "productTitle": "Smart Watch Classic",
    "description": "A classic design smartwatch with modern features.",
    "rating": 4,
    "price": 500,
    "seller": "GizmoHub",
    "totalSales": 910,
    "quantityInStock": 350,
    "keyword": "smart watch",

},
{
    "productID": 51,
    "productTitle": "Over-Ear Headphones",
    "description": "Comfortable over-ear headphones with deep bass.",
    "rating": 5,
    "price": 250,
    "seller": "GizmoHub",
    "totalSales": 1000,
    "quantityInStock": 410,
    "keyword": "Headphones",

},
{
    "productID": 52,
    "productTitle": "Wireless Earbuds",
    "description": "True wireless earbuds with noise isolation.",
    "rating": 4,
    "price": 180,
    "seller": "TechWorld",
    "totalSales": 1150,
    "quantityInStock": 350,
    "keyword": "Headphones",

},
{
    "productID": 53,
    "productTitle": "Gaming Headset",
    "description": "High-quality gaming headset with a built-in mic.",
    "rating": 5,
    "price": 300,
    "seller": "FutureGadgets",
    "totalSales": 880,
    "quantityInStock": 290,
    "keyword": "Headphones",

},
{
    "productID": 54,
    "productTitle": "Noise Cancelling Earbuds",
    "description": "Earbuds with active noise cancellation technology.",
    "rating": 4,
    "price": 220,
    "seller": "GizmoHub",
    "totalSales": 720,
    "quantityInStock": 470,
    "keyword": "Headphones",

},
{
    "productID": 55,
    "productTitle": "Over-Ear Studio Headphones",
    "description": "Studio-grade headphones with crystal-clear sound.",
    "rating": 5,
    "price": 350,
    "seller": "TechWorld",
    "totalSales": 980,
    "quantityInStock": 230,
    "keyword": "Headphones",

},
{
    "productID": 56,
    "productTitle": "In-Ear Headphones",
    "description": "Compact in-ear headphones with a comfortable fit.",
    "rating": 4,
    "price": 150,
    "seller": "FutureGadgets",
    "totalSales": 1100,
    "quantityInStock": 420,
    "keyword": "Headphones",

},
{
    "productID": 57,
    "productTitle": "Wireless Over-Ear Headphones",
    "description": "Wireless over-ear headphones with deep bass and clear treble.",
    "rating": 5,
    "price": 280,
    "seller": "GizmoHub",
    "totalSales": 920,
    "quantityInStock": 310,
    "keyword": "Headphones",

},
{
    "productID": 58,
    "productTitle": "Bluetooth Earphones",
    "description": "Lightweight Bluetooth earphones with a long battery life.",
    "rating": 4,
    "price": 170,
    "seller": "GizmoHub",
    "totalSales": 800,
    "quantityInStock": 460,
    "keyword": "Headphones",

},
{
    "productID": 59,
    "productTitle": "Over-Ear Wireless Headphones",
    "description": "Comfortable wireless headphones with a foldable design.",
    "rating": 5,
    "price": 300,
    "seller": "GadgetPlus",
    "totalSales": 720,
    "quantityInStock": 380,
    "keyword": "Headphones",

},
{
    "productID": 60,
    "productTitle": "Sports Earbuds",
    "description": "Sweat-resistant earbuds designed for sports and fitness.",
    "rating": 4,
    "price": 200,
    "seller": "TechWorld",
    "totalSales": 670,
    "quantityInStock": 330,
    "keyword": "Headphones",

}
]